[functions.auth-send-sms]
verify_jwt = false

[functions.fedapay-initialize]
verify_jwt = false

[functions.fedapay-verify]
verify_jwt = false

[functions.fedapay-webhook]
verify_jwt = false

[functions.payment-initialize]
verify_jwt = false

[functions.payment-verify]
verify_jwt = false

[functions.geniuspay-webhook]
verify_jwt = false

[functions.colis-sms-notify]
verify_jwt = false
