-- =============================================================================
-- Tibus — RLS ReservationBus DELETE (annulation voyageur)
-- Étape 9 — REPORTÉ
--
-- Ne pas exécuter tant que la politique anti-fraude est active :
-- aucun ticket non payé n'est créé en base, donc pas d'annulation pending à gérer.
-- Réactiver lorsque des réservations en attente existeront à nouveau (si jamais).
-- =============================================================================

-- CREATE POLICY "reservationbus_delete_own_pending" ON "ReservationBus"
--   FOR DELETE TO authenticated
--   USING (
--     "createdBy" = public.current_app_user_id()
--     AND "isReservation" = true
--     AND "type" = 'voyage'
--   );
