packages:
  - .

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild

blockExoticSubdeps: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@usehercules/*"
